"use client";

import { ApolloProvider } from "@apollo/client";
import { client } from "@repo/graphql/lib/apolloClient";

import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import theme from "./utils/theme";

const orgonRegular = localFont({
  src: "./fonts/Orgon-Regular.woff",
  variable: "--font-orgon-regular",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <title>ISA LAFAM</title>
      <meta name="description" content={'Sellers site for ISA LAFAM done in next14'} />
      <body className={orgonRegular.variable}>
        <ThemeProvider theme={theme}>
          <ApolloProvider client={client}>
            {children}
          </ApolloProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
